common:
  img_topic: "/cam0/image_raw"
  lid_topic: "/points_raw"
  imu_topic: "/imu_raw"
  img_en: 1
  lidar_en: 1
  ros_driver_bug_fix: false

extrin_calib:
  # Pose of LiDAR with respect to IMU
  extrinsic_T: [0.00000, 0.00000, -0.85000]
  extrinsic_R: [1.00000, 0.00000, 0.00000, 0.00000, 1.00000, 0.00000, 0.00000, 0.00000, 1.00000]

  # Pose of LiDAR with respect to Camera
  Rcl: [0.00000, 1.00000, 0.00000,
         0.00000, 0.00000, 1.00000,
         1.00000, 0.00000, 0.00000]
  Pcl: [0.05500, 0.00000, 0.00000]

time_offset: 
  imu_time_offset: 0.0
  img_time_offset: 0.0
  exposure_time_init: 0.0

preprocess:
  point_filter_num: 1
  filter_size_surf: 0.1
  lidar_type: 2
  scan_line: 16
  blind: 0.8

vio:
  max_iterations: 5
  outlier_threshold: 1000 # 78 100 156 #100 200 500 700 infinite
  img_point_cov: 100 # 100 1000 
  patch_size: 8
  patch_pyrimid_level: 4
  normal_en: true
  raycast_en: false
  inverse_composition_en: false
  exposure_estimate_en: true
  inv_expo_cov: 0.1

imu: # Same IMU noise values at LIO-SAM (perhaps we should just use FAST-LIVO2 defaults instead)
  imu_en: true
  imu_int_frame: 30
  acc_cov: 3.9939570888238808e-04
  gyr_cov: 1.5636343949698187e-04
  b_acc_cov: 6.4356659353532566e-06
  b_gyr_cov: 3.5640318696367613e-06

lio:
  max_iterations: 5
  dept_err: 0.02
  beam_err: 0.05
  min_eigen_value: 0.0025 # 0.005
  voxel_size: 0.5
  max_layer: 2
  max_points_num: 50
  layer_init_num: [5, 5, 5, 5, 5]

local_map:  
  map_sliding_en: false
  half_map_size: 100
  sliding_thresh: 8

uav:
  imu_rate_odom: true
  gravity_align_en: true

publish:
  dense_map_en: true # Maybe set to false for speed/computational reasons
  pub_effect_point_en: false 
  pub_plane_en: false
  pub_scan_num: 1
  blind_rgb_points: 0.0

evo:
  seq_name: "V2.4.C"
  pose_output_en: true

pcd_save:
  pcd_save_en: false
  type: 0 # 0: World Frame, 1: Body Frame;
  colmap_output_en: false # need to set interval = -1
  filter_size_pcd: 0.15
  interval: -1
  # how many LiDAR frames saved in each pcd file;
  # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.

image_save:
  img_save_en: false
  interval: 1
